import crypto from 'node:crypto';
import { NUCLEUS_ID, SOUL_MESH_PROTOCOL, type SoulMeshMessage, type SoulNucleus, handleMeshMessage } from './endpoint';
import { createSoulMeshNonce, signSoulMeshMessage } from './SoulMeshHmac';
export type MeshPeer = { id: Exclude<SoulNucleus, 'N05'>; url: string };
const CONTRACT_VERSION = '1.1.0' as const;
const PEER_ENV: Record<MeshPeer['id'], string> = { N01:'SOUL_MESH_N01_URL', N02:'SOUL_MESH_N02_URL', N03:'SOUL_MESH_N03_URL', N04:'SOUL_MESH_N04_URL', N06:'SOUL_MESH_N06_URL' };
export function getConfiguredPeers(): MeshPeer[] { return (Object.entries(PEER_ENV) as [MeshPeer['id'],string][]).map(([id,env])=>({id,url:process.env[env]?.trim().replace(/\/$/,'')??''})).filter(p=>Boolean(p.url)); }
export function createRequest(target: MeshPeer['id'], capability:string, payload:unknown):SoulMeshMessage { const id=crypto.randomUUID(); return {protocol:SOUL_MESH_PROTOCOL,contractVersion:CONTRACT_VERSION,id,correlationId:id,source:NUCLEUS_ID,target,kind:'request',capability,payload,timestamp:Date.now(),meta:{runtime:'nextjs-ai-chatbot',transport:'http-json',encoding:'json',version:SOUL_MESH_PROTOCOL,nonce:crypto.randomUUID()}}; }
function legacySignature(raw:string){const secret=process.env.SOUL_MESH_SIGNING_SECRET;if(!secret)return undefined;return crypto.createHmac('sha256',secret).update(raw).digest('hex');}
export async function sendToNucleus(target:MeshPeer['id'],capability:string,payload:unknown,timeoutMs=30000):Promise<unknown>{const peer=getConfiguredPeers().find(p=>p.id===target);if(!peer)throw new Error(`MESH_PEER_NOT_CONFIGURED:${target}`);const request=createRequest(target,capability,payload);const raw=JSON.stringify(request);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const headers:Record<string,string>={'content-type':'application/json',accept:'application/json'};if(process.env.SOUL_MESH_TOKEN)headers.authorization=`Bearer ${process.env.SOUL_MESH_TOKEN}`;const hmacSecret=process.env.SOUL_MESH_HMAC_SECRET?.trim();if(hmacSecret){const nonce=createSoulMeshNonce();headers['x-soul-mesh-nonce']=nonce;headers['x-soul-mesh-hmac']=signSoulMeshMessage(request,hmacSecret,nonce);}else{const sig=legacySignature(raw);if(sig)headers['x-soul-signature']=sig;}const response=await fetch(`${peer.url}/api/soul-mesh`,{method:'POST',headers,body:raw,cache:'no-store',signal:controller.signal});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(`MESH_HTTP_${response.status}`);if(!body||body.protocol!==SOUL_MESH_PROTOCOL||body.contractVersion!==CONTRACT_VERSION||body.correlationId!==request.correlationId||body.target!==NUCLEUS_ID)throw new Error('MESH_RESPONSE_INVALID');if(body.kind==='error')throw new Error(`MESH_REMOTE_ERROR:${body.payload?.code??'UNKNOWN'}`);return body.payload;}finally{clearTimeout(timer);}}
export async function invokePeerAI(target:MeshPeer['id'],prompt:string,options:{system?:string;model?:'chat-model'|'chat-model-reasoning';temperature?:number;maxOutputTokens?:number}={}){return sendToNucleus(target,'ai.infer',{prompt,...options});}
export async function probePeer(peer:MeshPeer){const started=Date.now();try{const details=await sendToNucleus(peer.id,'mesh.describe',{from:NUCLEUS_ID});return{id:peer.id,configured:true,reachable:true,latencyMs:Date.now()-started,details};}catch(error){return{id:peer.id,configured:true,reachable:false,latencyMs:null,error:error instanceof Error?error.message:String(error)};}}
export async function probeAllPeers(){return Promise.all(getConfiguredPeers().map(probePeer));}
export async function dispatchLocal(message:SoulMeshMessage,handlers:Record<string,(payload:unknown)=>Promise<unknown>|unknown>){return handleMeshMessage(message,handlers);}
export function assertCapabilityResult<T>(value:unknown, label:string):T{if(value===undefined||value===null)throw new Error(`MESH_EMPTY_RESULT:${label}`);return value as T;}
