export type SoulNucleus = 'N01'|'N02'|'N03'|'N04'|'N05'|'N06';
export type SoulMeshCapability = { id:string; version:string; description:string; request:boolean; response:boolean; events:boolean; owner?:SoulNucleus; execution?:'cognitive'|'tool'|'native'|'orchestration'|'observability'|'remote' };
export const SOUL_MESH_CAPABILITIES: SoulMeshCapability[] = [
  { id:'mesh.ping',version:'1.0',description:'Connectivity and liveness probe',request:true,response:true,events:false,owner:'N05',execution:'observability' },
  { id:'mesh.describe',version:'1.0',description:'Runtime, protocol and capability discovery',request:true,response:true,events:false,owner:'N05',execution:'observability' },
  { id:'core.health',version:'1.0',description:'N05 runtime health and readiness',request:true,response:true,events:false,owner:'N05',execution:'observability' },
  { id:'mesh.topology',version:'1.0',description:'Peer reachability and latency discovery',request:true,response:true,events:true,owner:'N05',execution:'observability' },
  { id:'ai.infer',version:'1.0',description:'Text inference executed by the N05 AI runtime',request:true,response:true,events:false,owner:'N05',execution:'cognitive' },
  { id:'conversation',version:'1.0',description:'Conversational services exposed by N05',request:true,response:true,events:true,owner:'N05',execution:'cognitive' },
  { id:'tool-execution',version:'1.0',description:'Execution of N05 AI tools through an authorized runtime adapter',request:true,response:true,events:false,owner:'N05',execution:'tool' },
  { id:'artifact-processing',version:'1.0',description:'Artifact creation and processing services',request:true,response:true,events:true,owner:'N05',execution:'tool' },
  { id:'document-processing',version:'1.0',description:'Document services',request:true,response:true,events:true,owner:'N05',execution:'tool' },
  { id:'context-orchestration',version:'1.0',description:'Context-aware orchestration for N05',request:true,response:true,events:true,owner:'N05',execution:'orchestration' },
  { id:'streaming',version:'1.0',description:'Streaming-capable AI response services',request:true,response:true,events:true,owner:'N05',execution:'cognitive' },
  { id:'mesh.handshake',version:'1.1',description:'N01 Mesh negotiation and capability discovery',request:true,response:true,events:false,owner:'N01',execution:'remote' },
  { id:'mesh.health',version:'1.1',description:'N01 runtime and transport health',request:true,response:true,events:true,owner:'N01',execution:'remote' },
  { id:'mesh.capabilities',version:'1.1',description:'N01 executable capability discovery',request:true,response:true,events:true,owner:'N01',execution:'remote' },
  { id:'cognitive.intent',version:'1.0',description:'N01 cognitive intent analysis',request:true,response:true,events:false,owner:'N01',execution:'remote' },
  { id:'agi.process',version:'1.0',description:'N01 AeternumAGI processing',request:true,response:true,events:true,owner:'N01',execution:'remote' },
  { id:'ai.reasoning',version:'1.0',description:'N01 provider-neutral reasoning adapter',request:true,response:true,events:true,owner:'N01',execution:'remote' },
  { id:'android.device_info',version:'1.0',description:'N01 Android device information',request:true,response:true,events:false,owner:'N01',execution:'remote' },
  { id:'android.battery',version:'1.0',description:'N01 Android battery state',request:true,response:true,events:true,owner:'N01',execution:'remote' },
  { id:'android.memory',version:'1.0',description:'N01 Android memory state',request:true,response:true,events:true,owner:'N01',execution:'remote' },
  { id:'android.network',version:'1.0',description:'N01 Android network state',request:true,response:true,events:true,owner:'N01',execution:'remote' },
];
